apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-cron
spec:
  # Cronjob will run every 5 minutes to stay alert in case of IP change.
  schedule: '*/5 * * * *'
  # keep last 12 hours worth of jobs.
  successfulJobsHistoryLimit: 144
  failedJobsHistoryLimit: 144
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns
            image: ghcr.io/cguertin14/ddns
            envFrom:
            - configMapRef:
                name: app-config
            env:
            # Warning: You need to define this secret in your config.
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GITHUB_TOKEN
                  name: tokens
            # Warning: You need to define this secret in your config.
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CLOUDFLARE_TOKEN
                  name: tokens
            resources:
              limits:
                cpu: 200m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 64Mi
          restartPolicy: OnFailure
