name: Build app

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.24'

      - name: Show Go version
        run: go version

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Build
        run: go build -o ddns